# Bullen configuration (defaults can be overridden here)
samplerate: 48000
frames_per_period: 128
nperiods: 2
inputs: 6
outputs: 2
record: true
recordings_dir: recordings
auto_connect_capture: true
auto_connect_playback: true
capture_match: capture
playback_match: playback
selected_channel: 1
backend: jack  # 'jack' for full functionality, 'dummy' to run without JACK (UI-only, no audio)
