# Bullen configuration (defaults can be overridden here)
samplerate: 48000
frames_per_period: 128
nperiods: 2
inputs: 6
outputs: 8
record: true
recordings_dir: recordings
record_queue_size: 64
auto_connect_capture: true
auto_connect_playback: true
capture_match: audioinjector
playback_match: audioinjector
selected_channel: 1
